name: aws-codedeploy

on:
  push:
    branches:
      - main
      - develop

env:
  S3_BUCKET_NAME: whiletrue-depoloy-s3
  AWS_REGION: ap-northeast-2
  CODEDEPLOY_NAME: whiletrue-codedeploy
  CODEDEPLOY_GROUP: whiletrue-deploy-group

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create Directory
        run: mkdir -p src/main/resources

      - name: Copy secret config content
        run: echo "${{ secrets.CONFIG_SECRET }}" > src/main/resources/application-secret.yml

      - name: Copy prod config content
        run: echo "${{ secrets.CONFIG_PROD }}" > src/main/resources/application-prod.yml

      - name: Grant Permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .

      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}

      - name: Upload to S3
        run: aws s3 cp --region $AWS_REGION ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
            --application-name $CODEDEPLOY_NAME \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name $CODEDEPLOY_GROUP \
            --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
